config/routes.rb
BookClub::Application.routes.draw do
  devise_for :users

  resources :books
  resources :users, except: [:create]
  match 'books_ratings' => 'books#ratings'

  resources :books, only: [:show] do
    resources :reviews, only: [:create, :destroy]
    resources :likes, only: [:create, :destroy]
    post :search, on: :collection
    post :sort, on: :collection
  end

  root :to => "books#index"

end

app/models/like.rb
class Like < ActiveRecord::Base
  attr_accessible :book_id, :user_id
  belongs_to :user
  belongs_to :book
end

app/controllers/likes_controller.rb
class LikesController < BooksController
  before_filter :find_book

  def create
    @like = Like.new
  	@like.user = current_user
  	@like.book = @book  
  	if !current_user.has_liked?(@book) && @like.save
  	  redirect_to @book, notice: "You Liked the book! Thanks"
  	else
  	  redirect_to @book, alert: "Sorry you couldn't like it!!"
  	end    	
  end

  def destroy
    @like = Like.find(params[:id])
    if @like.destroy
      redirect_to @book, notice: "You UnLiked the book!"
    else
      redirect_to @book, notice: "Sorry you couldn't unlike it!"
    end  	
  end

  def noadmin_redirect
  end

end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/likes/_like.html.erb
<% if current_user %>
<% if current_user.has_liked?(@book) %>
	<%= form_for @like, url: book_like_path(@book, @like), method: :delete do |f| %>
		<%= f.submit "Undo Like", class: "btn btn-primary" %> <%= pluralize @book.likes.count, 'person' %> <%= pluralize_second_without_count @book.likes.count, 'like' %> this book!
	<% end %>
<% else %>
  <p><%= link_to raw('<i class=\'icon-thumbs-up icon-white\'></i> Like'),
  	book_likes_path(@book), 
	  class: "btn btn-primary",
	  method: :create %> <%= pluralize @book.likes.count, 'person' %> <%= pluralize_second_without_count @book.likes.count, 'like' %> this book!
	<% end %></p>
<% else %>
 <p>Please <%= link_to "sign in", new_user_session_path, :class => "mybutton", :style=> "color: #FFFFFF"%> to like this book or write a review...</p>
 <%= pluralize( @book.likes.count, 'person') %> likes this book!
<% end %>