config/routes.rb
BookClub::Application.routes.draw do
  devise_for :users

  resources :books
  resources :users, except: [:create]
  match 'books_ratings' => 'books#ratings'

  resources :books, only: [:show] do
    resources :reviews, only: [:create, :destroy]
    resources :likes, only: [:create, :destroy]
    post :search, on: :collection
    post :sort, on: :collection
  end

  root :to => "books#index"

end

app/models/book.rb
class Book < ActiveRecord::Base
  attr_accessible :author, :description, :title, :book_type

  validates :title, presence: true
  validates :author, presence: true

  has_many :reviews, dependent: :destroy
  
  has_attached_file :pic, :styles => 
           { :medium => "300x400>", :thumb => "100x100>" }
  has_attached_file :attach
  attr_accessible :pic, :attach

  has_many :likes
  has_many :users, through: :likes

  BOOK_TYPES = ["Fiction", "Mystery", "Fantasy", "Arts", "Business","History", "Sciences", "Health","Travel"]
  ALL = "All" 
  TYPE = "Type"
  AUTHOR = "Author"
  TITLE = "Title"
  LIKES_COUNT = "Likes Count"
  SORT_BY = "Sort by "
  SEARCH_TYPES = [ALL, TITLE, AUTHOR, TYPE]
  ORDER_TYPES = [SORT_BY+LIKES_COUNT, SORT_BY+TITLE, SORT_BY+AUTHOR, SORT_BY+TYPE]
  def self.search_for(search_type, keyword)
    search_condition = "%" + keyword + "%"
    if search_type == ALL
      find(:all, :conditions => ['title LIKE ? OR author LIKE ? OR book_type LIKE ?', search_condition, search_condition, search_condition])
  	elsif search_type == TYPE
      find(:all, :conditions => ['book_type LIKE ?',  search_condition], :order =>'title ASC')
  	elsif search_type == AUTHOR
      find(:all, :conditions => ['author LIKE ?', search_condition])
  	elsif search_type == TITLE
     find(:all, :conditions => ['title LIKE ?', search_condition])
  	else
  		[]
  	end
  end

  def self.all_ordered(order_type=SEARCH_ALL)
    if order_type == SORT_BY+LIKES_COUNT
      all.sort_by(&:likes_count).reverse.map    
    elsif order_type == SORT_BY+TITLE
      find(:all, :order =>'title ASC')
    elsif order_type == SORT_BY+AUTHOR
      find(:all, :order =>'author ASC')
    elsif order_type == SORT_BY+TYPE
     find(:all, :order =>'book_type ASC')
    else
      []
    end
  end

  def likes_count
    likes.count
  end  

end

app/controllers/books_controller.rb
require 'google_chart' 

class BooksController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :show, :search, :sort, :ratings]
  before_filter :find_book, only: [:show, :edit, :update, :destroy]
  before_filter :noadmin_redirect, only: [:new, :edit, :update, :create, :destrory] 
  # GET /books
  # GET /books.json
  def index
    @books = Book.all.sort_by(&:likes_count).reverse.map    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @books }
    end
  end

  def ratings
    @books = Book.all.sort_by(&:likes_count).reverse.map
    
    pc_data = {}

    i = 0
    @books.each do |book|
      h1 = { book.title => book.likes.count }
      pc_data = pc_data.merge(h1)
      i = i + 1
      if i == 5 
        break;
      end
    end

    # pc.data key, value
    h = pc_data.length * 55 + 50 
    lc = GoogleChart::BarChart.new("700x" + h.to_s, "", :horizontal, false)
    lc.show_legend = false
    lc.axis :x, :color => '333333', :font_size => 10, :alignment => :center, :range => [0,pc_data.values.max]
    lc.axis :y, :color => '333333', :font_size => 20, :alignment => :right, :labels => pc_data.keys.reverse
    lc.width_spacing_options(:bar_width => 50, :bar_spacing => 5) 
    lc.data "Books", pc_data.values, '3caae8'
  
    @chart_url = lc.to_url

    respond_to do |format|
      format.html # ratings.html.erb
      format.json { render json: @chart_url }
    end
  end

  # GET /books/1
  # GET /books/1.json
  def show
    @review = Review.new
    @like   = (current_user && current_user.like_for(@book)) || Like.new

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @book }
    end
  end

  # GET /books/new
  # GET /books/new.json
  def new
    @book = Book.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @book }
      end
  end

  # GET /books/1/edit
  def edit
    @book = Book.find(params[:id])
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(params[:book])

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render json: @book, status: :created, location: @book }
      else
        format.html { render action: "new" }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /books/1
  # PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update_attributes(params[:book])
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    if @book.destroy
      respond_to do |format|
        format.html { redirect_to books_url, notice: "Book entry is deleted successfully"  }
        format.json { head :no_content }
      end
    else
      format.html { redirect_to books_url, notice: "Book entry is not deleted."  }
    end
  end

  def search
    @search_type = params[:search_type]
    @books = Book.search_for params[:search_type], params[:search]
  end

  def sort
    @sort_type = params[:sort_type]
    @books = Book.all_ordered params[:sort_type]
  end

  private

  def find_book
    @book = Book.find( params[:book_id] || params[:id])
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_book.html.erb
<h2> <%= @book.title %> </h2>

<table width="100%" border="0">
  <tr>
    <td><%= render 'book_picture' %></td>
    <td>&nbsp;</td>
    <td><%= render 'book_details' %></td>
  </tr>
</table>

app/views/books/_book_details.html.erb
<p>
  <b>By:</b>
  <%= @book.author %>
</p>

<p>
  <b>Type:</b>
  <%= @book.book_type %>
</p>

<p>
  <b>Description:</b>
  <div class="well" style="margin-right:2cm">
    <%= @book.description %>
  </div>
</p>
<% if @book.attach and @book.attach.file? %>
  <%= link_to raw('<i class=\'icon-file icon-white\'></i> File attached'),
    @book.attach.url, class: "btn btn-primary"%> 
    <br/>
 <%end%>

app/views/books/_book_picture.html.erb
<div class="images_container">
  <div class="book_image" id="book_image">
  <% if @book.pic and @book.pic.file? %>
    <%= image_tag @book.pic.url(:medium), class: "img-polaroid main_image" %>
  <% else %>
   <p>No image has been added for this book yet...</p>
  <% end %>
  <div>
</div>
<br/>

app/views/books/_form.html.erb
<%= form_for(@book) do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title, :style => "width:400px;" %>
  </div>
  <div class="field">
    <%= f.label "By" %>
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :type %>
    <%= f.select(:book_type, Book::BOOK_TYPES) %>  
  </div>
  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description, :style => "width:400px", rows: 5 %>
  </div>

   <p>
     <b> Picture </b><br/>
     <%= f.file_field :pic %>
   </p>  

   <p>
     <b> Attachment </b><br/>
     <%= f.file_field :attach %>
  </p>

  <div class="actions">
    <%= f.submit class: "btn btn-primary"%>
  </div>
<% end %>

app/views/books/_list_books.html.erb
<div style="margin-right:2cm" >
<table class="table table-striped table-bordered table-condensed" >
  <tr>
    <th>Title</th>
    <th>By</th>
    <th>Type</th>
 </tr>

<% @books.each do |book| %>
  <tr>
    <td><strong><%= link_to book.title, book, :class => "listitem" %></strong></td>
    <td class="listitem"><%= book.author %></td>
    <td class="listitem"><%= book.book_type %></td>
  </tr>
<% end %>
</table>
</div>

app/views/books/_reviews.html.erb
<h2> Reviews </h2>
<%if @book.reviews.empty? %>
  "no review"
<%else%>

  <% @book.reviews.each do |review| %>
    <% if review.user  %>      
   	  <div class="well" style="margin-right:2cm">
        <% if review.user.pic.file? %>
          <div class="thumbnail pull-left review-avatar">
            <%= image_tag review.user.pic.url(:thumb) %>
          </div>
        <% end %>      

        <p> Created at: <%= formatted_date review.created_at %> ;&nbsp; by: <%=review.user.name %></p>
  		  <p> <%= review.content %> </p>
        <% if @is_current_user_admin or (current_user && current_user.id == review.user_id) %>     
          <%= link_to "Delete review", book_review_path(@book, review), method: :delete, confirm: "Are you sure you want to delete this review", :class => "mybutton", :style=> "color: #FFFFFF" %>
        <% end %>
      </div>
    <% end %>
  <% end %>

<% end %>

app/views/books/_search.html.erb
  <%= form_tag search_books_path, class: "form-search"  do  %>
  <% @search_type = "All" unless @search_type %> 
    <%= select_tag :search_type, options_for_select(Book::SEARCH_TYPES, @search_type) %> 
    <%= text_field_tag :search, params[:search], :id => 'search_field' %>
    <%= button_tag(type: 'submit', class: "btn btn-primary") do %>
      <i class="icon-search icon-white"></i> Search
    <% end %>
  <% end %> 

app/views/books/_sort_by.html.erb
  <%= form_tag sort_books_path, class: "form-search" do  %>
  <% @sort_type = "All" unless @sort_type %> 
    <%= select_tag :sort_type, options_for_select(Book::ORDER_TYPES, @sort_type), onchange: "$(this).parent('form').submit();" %> 
  <% end %> 

app/views/books/edit.html.erb
<h1>Editing book</h1>

<%= render 'form' %>

<%= link_to 'Show', @book, :class => "mybutton", :style=> "color: #FFFFFF"  %>
<%= link_to 'Back', books_path, :class => "mybutton", :style=> "color: #FFFFFF" %>

app/views/books/index.html.erb
<p id="notice"><%= notice %></p>
<br />
<%= render 'search' %>

<br />
<h1>Listing books</h1>

<%= render 'list_books' %>

<br />

<% if @is_current_user_admin  %>    
  <%= link_to 'New Book', new_book_path, :class => "mybutton", :style=> "color: #FFFFFF" %>
<% end %>

app/views/books/new.html.erb
<h1>New book</h1>

<%= render 'form' %>

<%= link_to 'Back', books_path, :class => "mybutton", :style=> "color: #FFFFFF" %>

app/views/books/search.html.erb
<h1>Listing Search Results</h1>
<% if @books.count == 0 %>
 No book is found.
<% else %>
  <%= render 'list_books' %>
<%end%>
 <br/>
<br/>
<%= link_to 'Back', books_path, :class => "mybutton", :style=> "color: #FFFFFF" %> 

app/views/books/show.html.erb
<h2> <%= @book.title %> </h2>


<p>
  <b>By:</b>
  <%= @book.author %>
</p>

<p>
  <b>Type:</b>
  <%= @book.book_type %>
</p>

<p>
  <b>Description:</b>
  <div class="well" style="margin-right:2cm">
    <%= @book.description %>
  </div>
</p>
<hr>
<%= render 'likes/like' %>

<hr/>
<h2> Reviews </h2>
<%if @book.reviews.empty? %>
  "no review"
<%else%>

  <% @book.reviews.each do |review| %>
    <% if review.user %> 
     	<div class="well" style="margin-right:2cm">
        <p> Created at: <%= formatted_date review.created_at %> ;&nbsp; by: <%=review.user.name %></p>
    		<p> <%= review.content %> </p>
        <% if @is_current_user_admin or (current_user && current_user.id == review.user_id) %>     
          <%= link_to "Delete review", book_review_path(@book, review), method: :delete, confirm: "Are you sure you want to delete this review", :class => "mybutton", :style=> "color: #FFFFFF" %>
        <% end %>
      </div>
    <% end %>
  <% end %>

<% end %>

<br/>

<% if user_signed_in? %>
  <%= form_for @review, url: book_reviews_path(@book) do |f| %>
    <%= f.text_area :content, :rows => 5, :cols => 80, :class => "input-xxlarge" %>
    <%= f.submit class: "btn btn-primary" %>
  <% end %>
<% end %> 

<% if @is_current_user_admin %>    
  <%= link_to 'Edit', edit_book_path(@book), :class => "mybutton", :style=> "color: #FFFFFF" %> &nbsp;
  <%= link_to 'Delete', @book, method: :delete, :class => "mybutton", :style=> "color: #FFFFFF", data: { confirm: 'Are you sure?' } %>&nbsp;
<% end %>
<%= link_to 'Back', books_path, :class => "mybutton", :style=> "color: #FFFFFF" %>

app/views/books/sort.html.erb
<%= render 'index' %>